In [1]:
import pandas as pd
import numpy as np

In [3]:
sales_amount = np.random.randint(0,20, (5,3))
sales_amount

array([[17, 19,  8],
       [ 7, 13,  6],
       [ 9,  9,  8],
       [ 7, 12, 18],
       [ 6,  3, 19]])

In [4]:
weekly_sales = pd.DataFrame(sales_amount,
                            index = ["Mon","Tue","Wed","Thur","Fri"],
                            columns=["Asus","HP","Mac"])
weekly_sales

Asus  HP  Mac
Mon     17  19    8
Tue      7  13    6
Wed      9   9    8
Thur     7  12   18
Fri      6   3   19

In [5]:
# Creating Price dataFrame
prices = np.array([100,120,500])
prices

array([100, 120, 500])

In [6]:
prices.shape

(3,)

In [7]:
weekly_sales.shape

(5, 3)

In [8]:
daily_prices = prices.dot(weekly_sales.T)

In [9]:
daily_prices

array([ 7980,  5260,  5980, 11140, 10460])

In [10]:
# Add the daily prices as a column to the dataFrame
weekly_sales["Total ($)"] = daily_prices
weekly_sales

Asus  HP  Mac  Total ($)
Mon     17  19    8       7980
Tue      7  13    6       5260
Wed      9   9    8       5980
Thur     7  12   18      11140
Fri      6   3   19      10460

In [14]:
prices_df = pd.DataFrame(prices.reshape(1,3),
                         index=["Prices"],
                         columns=["Asus","HP","Mac"])
prices_df

Asus   HP  Mac
Prices   100  120  500